# Generated by Django 4.1.1 on 2022-10-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('Integration', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
