# Generated by Django 4.1.1 on 2022-10-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leia_atlassian', '0001_initial'),
    ]

    operations = [
    ]
