# Generated by Django 4.1.1 on 2022-10-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leia_atlassian', '0002_auto_20221009_0447'),
    ]

    operations = [
    ]
